global using System.Runtime.Serialization;
global using AutoMapper;
global using Microsoft.Extensions.Logging;
global using Moq;
global using CursoResidencia.Application.Common.Mappings;
global using CursoResidencia.Application.CreateHelloWorld;
global using CursoResidencia.Domain.Enums;
global using CursoResidencia.Domain.Models;
global using Xunit;
